# Generated by Django 4.2.2 on 2023-06-14 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.basemodel')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('cash', 'Cash'), ('credit', 'Credit')], default='debit', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('finance.basemodel',),
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.basemodel')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=7)),
            ],
            bases=('finance.basemodel',),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.basemodel')),
                ('spend', models.FloatField(blank=True, default=0, null=True)),
                ('income', models.FloatField(blank=True, default=0, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccount')),
                ('type', models.ManyToManyField(blank=True, to='finance.recordtype')),
            ],
            bases=('finance.basemodel',),
        ),
    ]
