# Generated by Django 4.2.2 on 2023-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_bankaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
