# Generated by Django 4.2.2 on 2023-06-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_record_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
