# Generated by Django 4.2.2 on 2023-06-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_recordtype_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtype',
            name='user',
        ),
    ]
