# Generated by Django 4.2.2 on 2023-06-14 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_bankaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_records', to='finance.bankaccount'),
        ),
    ]
