# Generated by Django 4.2.2 on 2023-06-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_bankaccount_user'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
